services:
  db:
    volumes:
      - ../keytrack-data/db:/var/lib/postgresql/data
  app:
    build:
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: "development"
    volumes:
      - .:/app
      - ../keytrack-data/uploads:/app/uploads
    command: pnpm dev
