FROM node:lts-alpine
WORKDIR /app

RUN corepack enable pnpm && \
  mkdir -p /app/uploads/scores

COPY package.json pnpm-lock.yaml* .npmrc* pnpm-workspace.yaml ./
RUN pnpm install

EXPOSE 3000
CMD ["pnpm", "dev"]
